### ISSUE TITLE
Random seeds

### ISSUE THREAD

**Issue by VolodyaCO** [AndreiChertkov/ttopt#1]
Hello, thank you for the very good package that you have open-sourced.

I wanted to ask if there's a plan to expose random number generators. There are places in the code where you use random number generation, but this is not reproducible in the sense that no random seeding is exposed to the user.

Thank you

**Comment by AndreiChertkov** [comment]
Dear @VolodyaCO,

thank you for your interest in our software product! ;)

Your question is very correct and logical, however, within the framework of the current implementation of the method, it seems that there is no need to manually set a random seed, instead, it is easier to manually set the initial TT-approximation `Y0` if necessary (please, see the function [ttopt_init](https://github.com/AndreiChertkov/ttopt/blob/899356268ee4bf0904ff33add80a4a8342bc94cc/ttopt/ttopt_raw.py#L186)). It will looks something like this:

```python
import numpy as np
from ttopt import TTOpt
from ttopt import ttopt_init

d = 10       # Dimension
n = [5]*d    # Mode size
rmax = 5     # TT-rank

tto = TTOpt(...args...)

np.random.seed(42)
Y0 = ttopt_init(n, rmax) # Initial TT-appr.

tto.minimize(rmax, Y0)
```

Apart from building an initial approximation `Y0`, the random number generator is used only if the `minimize` / `maximize` method is called with flags `add_rnd_inner` or `add_rnd_outer`. However, the use of these flags is not recommended, since in all our experiments it did not lead to an improvement in the optimization result.

Best regards,
Andrei.

**Comment by VolodyaCO** [comment]
Ohh ok thank you!

**Comment by VolodyaCO** [comment]
Hi @AndreiChertkov, I found your answer helpful, however I needed to rewrite `ttopt_init` to use a random state generator instead of a global random seed, like this:

```python
def _ttopt_init(n, rmax, rng: np.random.Generator, Y0=None, with_rank=False):
    """Build initial approximation for the main algorithm."""
    d = len(n)

    r = [1]
    for i in range(1, d):
        r.append(min(rmax, n[i - 1] * r[i - 1]))
    r.append(1)

    if Y0 is None:
        Y0 = [rng.normal(size=(r[i], n[i], r[i + 1])) for i in range(d)]

    if with_rank:
        return Y0, r
    else:
        return Y0
```

I don't know if you could find this useful, but this gets rid of having to manually set a global seed for all of numpy.

**Comment by AndreiChertkov** [comment]
@VolodyaCO , thank you for your suggestion! I took it into account in the latest version of the package (0.6.1). Please refer to the updated function interfaces:
- https://github.com/AndreiChertkov/ttopt/blob/8261db306483d7ccc182e85f7638c1889ada6c27/ttopt/ttopt.py#L479
- https://github.com/AndreiChertkov/ttopt/blob/8261db306483d7ccc182e85f7638c1889ada6c27/ttopt/ttopt_raw.py#L187

**Comment by VolodyaCO** [comment]
Oh this is fantastic, thanks a lot!
